version: 0.1         
phases:
  install:
    commands:
      - echo "Setting up MongoDB"
      - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
      - echo "deb http://repo.mongodb.org/apt/ubuntu "$(lsb_release -sc)"/mongodb-org/3.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.0.list
      - sudo apt-get update
      - sudo apt-get install -y mongodb-org
      - service mongod status
  pre_build:
    commands:
      - echo "Pulling in Davis dependencies"
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm test
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - package.json
    - gulpfile.js
    - lib/**/*
    - web/**/*
    - bin/*