version: '2'
services:
  mongo:
    image: mvertes/alpine-mongo
    ports:
      - "27017:27017"
    command: "mongod --smallfiles --logpath=/dev/null"
  node:
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
    environment:
      MONGODB_URI: mongodb://mongo/davis
      PORT: 3000
