database:
    dsn: '127.0.0.1:27017/davis-test'
watson:
    enabled: true
    stt:
        user: 'ab09e971-9582-46c1-9672-7a0920c3a1dd'
        password: 'hHqQVkHQSIKV'
    tts:
        user: '14fcca52-7f8b-449a-a60c-535f20cdbf09'
        password: 'uDg43gTfgZii'